### PR TITLE
v0.4.0

### PR DESCRIPTION
**Pull request by nsheff**
Adds asset detail page.

### CODE REVIEW

**Comment by nsheff** [comment]
I'm a bit confused -- the staging server is already showing these updates, but this is still on dev and hasn't been merged to staging yet... did I miss something?

**Comment by stolarczyk** [comment]
I'm not sure what's the reason either. We've encountered this situation before and forgot to ask Neal..

@nmagee is that an expected behavior?

**Comment by nmagee** [comment]
I'll check on this. Maybe in some sleepy stupor I got the branches switched when setting up the deployments? I thought it was all settled. I'll report back in just a bit.

**Comment by nmagee** [comment]
@michalstolarczyk I see at least two issues:

1. The `dev` branch has no deployment trigger in `.travis.yml` yet. I'm adding that in a minute.

2. The dev container is throwing some python errors when I try to redeploy it in the DCOS cluster:

```
Preparing rootfs at '/var/lib/mesos/slave/provisioner/containers/b8bf4b12-4a54-4e06-b367-a507e29ff552/backends/overlay/rootfses/dae1ccec-d863-422a-9bc0-e65c51e07da9'
Marked '/' as rslave
Changing root to /var/lib/mesos/slave/provisioner/containers/b8bf4b12-4a54-4e06-b367-a507e29ff552/backends/overlay/rootfses/dae1ccec-d863-422a-9bc0-e65c51e07da9
email-validator not installed, email fields will be treated as str.
To install, run: pip install email-validator
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/attmap/ordattmap.py", line 45, in __getitem__
    return super(OrdAttMap, self).__getitem__(item)
KeyError: 'genome_server'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/refgenconf/refgenconf.py", line 95, in __init__
    self[CFG_SERVER_KEY] = self[CFG_SERVER_KEY].rstrip("/")
  File "/usr/local/lib/python3.7/site-packages/attmap/pathex_attmap.py", line 51, in __getitem__
    v = super(PathExAttMap, self).__getitem__(item)
  File "/usr/local/lib/python3.7/site-packages/attmap/ordattmap.py", line 47, in __getitem__
    return AttMap.__getitem__(self, item)
  File "/usr/local/lib/python3.7/site-packages/attmap/attmap.py", line 32, in __getitem__
    return self.__dict__[item]
KeyError: 'genome_server'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/refgenieserver", line 10, in <module>
    sys.exit(main())
  File "/app/refgenieserver/main.py", line 120, in main
    rgc = RefGenConf(select_genome_config(args.config))
  File "/usr/local/lib/python3.7/site-packages/refgenconf/refgenconf.py", line 97, in __init__
    raise MissingConfigDataError(CFG_SERVER_KEY)
refgenconf.exceptions.MissingConfigDataError: genome_server
I1121 08:36:24.011921     7 executor.cpp:1039] Command exited with status 1 (pid: 12)
```

**Comment by stolarczyk** [comment]
What do you mean by "dev container"? We just have files for `master`(`Dockerfile`) and `staging`(`staging.Dockerfile`). 

As for the error --  it is clearly coming from `refgenconf` version incompatibility. It looks like it uses  version (<0.5.3) which expects `genome_server` key in the config, but we switched to `genome_servers`. 
So rebuilding the container that produces the error should solve that, because the `refgenconf v0.5.3` has been released almost a month ago.

**Comment by nsheff** [comment]
@nmagee we are not intending to run a dev instance. just staging and master.

**Comment by nmagee** [comment]
Okay, yeah we had a dev container running, probably from the primordial version of things that I left up running. There are now only staging and master versions running:

http://staging.refgenomes.databio.org/
http://refgenomes.databio.org/

I see now why this pushed through to staging even though it was only a PR: Travis has a setting to go ahead and pre-build for PRs -- it's another step you can use to make sure your post-PR build is going to be successful, and is one of the checks listed in the box at the bottom of this PR. 

See https://travis-ci.org/databio/refgenieserver/pull_requests and you'll see it was built 16 hours ago.

This can be switched off here: https://travis-ci.org/databio/refgenieserver/settings and toggling the **Build Pushed Pull Requests** switch near the top of the settings. I think this is on by default, so may be something we never worried about before?

**Review by stolarczyk — APPROVED** [review]

**Pull request merged**
