### PR TITLE
v0.3.0

### PR DESCRIPTION
**Pull request by stolarczyk**
to do:
- [x] release date

### CODE REVIEW

**Comment by nsheff** [comment]
Ok is this ready to go?

**Comment by stolarczyk** [comment]
yes, ready

**Comment by stolarczyk** [comment]
Now we just need to swap the directory names in $PROJECT so that it uses the right genome archive

**Comment by nsheff** [comment]
Ok I copied over genomes_staging to genomes.

**Comment by stolarczyk** [comment]
it's `refgenomes_*` directory that is used by refgenieservesr. But I've copied it a few mins ago

**Comment by stolarczyk** [comment]
#51 is caused by refgenconf not being installed. I left it commented out in the requirements file

**Pull request merged**
