### PR TITLE
stage 0.5.2 

### LINKED ISSUE #31: add examples to api docs
the swagger autodocs should include examples. right now it says 'none available'.

we just need to add examples in the code in the appropriate way to give users example queries they can try out.

### LINKED ISSUE #38: endpoint to identify genome by hash?
Will we want to be able to return server metadata for a genome that is requested by hash value?

### LINKED ISSUE #89: add id-digest conversion endpoints
Add API endpoint that converts a human-readable identifier to the server's digest and vice versa

### LINKED ISSUE #101: How should URLs be formatted?
Currently, genome splash pages, asset pages, et cetera follow a non-uniform URL structure. 

For example, a genome splash page utilizes a parental `genome/` URL: `http://rg.databio.org/genome/10c566e9f7c867a2eb27fd8606254a5a3d45aee8c175a07e/splash`

But, a related asset _for_ that genome changes the structure to: `
http://rg.databio.org/v3/asset/10c566e9f7c867a2eb27fd8606254a5a3d45aee8c175a07e/bowtie2_index/splash?tag=default`

A few thoughts:
1. Enabling human-readable URL entry.
Current: `http://rg.databio.org/genome/10c566e9f7c867a2eb27fd8606254a5a3d45aee8c175a07e/splash`
Instead: `http://rg.databio.org/genome/hg19/splash`
 - Both go to the same place essentially. And then the URL construction could also change...
2. Changing the URL structure to go from most broad -> most specific. e.g.
`http://rg.databio.org/index/hg19` # splash page
`http://rg.databio.org/index/asset/recipe/bowtie2_index/hg19` # asset endpoint _for_ the recipe _for_ bowtie2_index _for_ hg19
 - Therefore, if I wanted to see how this was different for hg38, I could just manually change that in the URL itself as opposed to needing to browse back to the refgenomes home page and finding that genome splash page.
3. Alternatives to `asset/`.  Maybe this doesn't need it's own `/`, but could be:
```
asset_archive/bowtie2_index/hg38
asset_digest/bowtie2_index/hg38
asset_recipe/bowtie2_index/hg38
```

### PR DESCRIPTION
**Pull request by nsheff**
Need this to deploy test servers on aws.

### CODE REVIEW

**Comment by nsheff** [comment]
AWS reports this error:

```
docker logs 9294c7f25542 --tail 100
Traceback (most recent call last):
  File "/usr/local/bin/refgenieserver", line 10, in <module>
    sys.exit(main())
  File "/app/refgenieserver/main.py", line 46, in main
    from .routers import version1, version2, version3
  File "/app/refgenieserver/routers/version3.py", line 9, in <module>
    from yacman import UndefinedAliasError
ImportError: cannot import name 'UndefinedAliasError' from 'yacman' (/usr/local/lib/python3.7/site-packages/yacman/__init__.py)
```

**Comment by nsheff** [comment]
I guess we'd need to release yacman before we can deploy these staging tests.

**Comment by stolarczyk** [comment]
once you deploy an instance let me know if the new index and genome splash pages are good to go.

**Comment by nsheff** [comment]
I've redeployed after the update to yacman, but it's giving the same error.

yacman is updating correctly:

```
docker run -it --entrypoint sh 235728444054.dkr.ecr.us-east-1.amazonaws.com/my-ecr-repo:bd8804eb2c74f31038d84c087b04aa51295d71c3
/app # python
Python 3.7.3 (default, Mar 27 2019, 23:51:31) 
[GCC 6.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import yacman
>>> yacman.__version__
'0.7.0'
```

**Comment by nsheff** [comment]
I take it back, the error is different now:

```
 docker logs 4fdc5ea9be95
Traceback (most recent call last):
  File "/usr/local/bin/refgenieserver", line 10, in <module>
    sys.exit(main())
  File "/app/refgenieserver/main.py", line 46, in main
    from .routers import version1, version2, version3
  File "/app/refgenieserver/routers/version3.py", line 75, in <module>
    @router.get("/genomes_dict", operation_id=API_VERSION + API_ID_GENOMES_DICT)
NameError: name 'API_ID_GENOMES_DICT' is not defined
```

**Comment by stolarczyk** [comment]
this is a constant variable introduced in the latest refgenconf. Naturally, refgenieserver depends of dev refgenconf since it uses the new config format etc

**Comment by stolarczyk** [comment]
is it possible to use the dev version from github, not a released one for now?

**Comment by nsheff** [comment]
yeah I thought it might be that. this is tricky. the staging container could grab and install the dev refgenconf theoretically.

**Comment by nsheff** [comment]
There already is a staging dockerfile that does this:

https://github.com/refgenie/refgenieserver/blob/dev/staging.Dockerfile

we're just not deploying it correctly...

**Comment by nsheff** [comment]
Ok, on to the next issue :) 

```
Traceback (most recent call last):
  File "/usr/local/bin/refgenieserver", line 10, in <module>
    sys.exit(main())
  File "/app/refgenieserver/main.py", line 37, in main
    rgc = RefGenConf(filepath=selected_cfg, writable=False)
  File "/usr/local/lib/python3.7/site-packages/refgenconf/refgenconf.py", line 101, in __init__
    raise ConfigNotCompliantError(msg)
refgenconf.exceptions.ConfigNotCompliantError: This genome config (v0.3) is not compliant with v0.4 standards. To use it, please downgrade refgenie: 'pip install "refgenie>=0.7.0,<0.10.0"'; For config format documentation please see http://refgenie.databio.org/en/latest/genome_config/
```

Need to provide a 0.4 example config file

**Comment by nsheff** [comment]
any way to easily convert a file from 0.3 to 0.4? I can't think of a way to easily make a new config file... I don't suppose it's possible since the genome digests are such a big difference.

**Comment by stolarczyk** [comment]
> any way to easily convert a file from 0.3 to 0.4?

There's no way currently. You're right, that would take some effort to implement a format converter. Not sure if it's worth it.

I'm confused. Don't you have a 0.4 version? I thought you're trying to deploy an instance for the plantref archives, which were just generated with the dev refgenconf etc?

**Comment by nsheff** [comment]
> I'm confused. Don't you have a 0.4 version? I thought you're trying to deploy an instance for the plantref archives, which were just generated with the dev refgenconf etc?

Yeah I do, but the staging server is using the primary repo for its demo data :smile:

anyway I can just add that I guess.

**Comment by nsheff** [comment]
it works! http://refgenomes.databio.org:82/

**Comment by stolarczyk** [comment]
awesome!

**Comment by nsheff** [comment]
This is a major API revamp, right? Should probably be 0.6.0, no?

**Comment by stolarczyk** [comment]
Tested with an instance deployed via https://github.com/refgenie/test-data at http://rg.databio.org:82:

- API v2 serves archives formatted the old way: http://rg.databio.org:82/v2/asset/rCRSd/fasta/archive?tag=default
- API v3 serves archives formatted the new way: http://rg.databio.org:82/v3/asset/511fb1178275e7d529560d53b949dba40815f195623bce8e/fasta/archive?tag=default

**Pull request merged**
